version: '3'

services:
  roaddataetl:latest:
    image: roaddataetl:latest

    volumes:
    - ./$AIRFLOW_HOME:/opt/airflow

    ports:
    - "8080:8080"

    command: airflow standalone

  
